# Generated by Django 4.2.7 on 2023-12-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=4)),
                ('phone_number', models.CharField(max_length=9)),
                ('is_verify', models.CharField(max_length=4)),
            ],
        ),
    ]
