# Generated by Django 4.2.7 on 2023-12-03 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referal', '0003_referal_verify_delete_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referal',
            name='invited_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referal',
            name='referal_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referal_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verify',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
